# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AdguardhomeExporter < Formula
  desc "Prometheus adguardhome exporter"
  homepage "https://github.com/sfragata/adguardhome_exporter/"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sfragata/adguardhome_exporter/releases/download/v1.0.0/adguardhome_exporter_1.0.0_darwin_arm64.tar.gz"
      sha256 "e45e073016216a846730661262704373b717657c98aaf796f91758bfe1389d5b"

      def install
        bin.install "adguardhome_exporter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sfragata/adguardhome_exporter/releases/download/v1.0.0/adguardhome_exporter_1.0.0_darwin_amd64.tar.gz"
      sha256 "b03244a6c0ddde9822ad80337f5af3a26b66086b2cb9dc589dfbc80a2ab617e3"

      def install
        bin.install "adguardhome_exporter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sfragata/adguardhome_exporter/releases/download/v1.0.0/adguardhome_exporter_1.0.0_linux_amd64.tar.gz"
      sha256 "e3eb88052a98136e970bbe9da9d2bdfc1921879a6d7826bd05047bbcc9754916"

      def install
        bin.install "adguardhome_exporter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sfragata/adguardhome_exporter/releases/download/v1.0.0/adguardhome_exporter_1.0.0_linux_arm64.tar.gz"
      sha256 "d445123d5cc793141126b46907cf90a465aac68991f3a1319a469d08281eaa50"

      def install
        bin.install "adguardhome_exporter"
      end
    end
  end
end
