# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AlertmanagerWebhookLogger < Formula
  desc "Webhook to log json sent from alertmanager"
  homepage "https://github.com/sfragata/alertmanager-webhook-logger/"
  version "1.0.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sfragata/alertmanager-webhook-logger/releases/download/v1.0.0/alertmanager-webhook-logger_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "42931cf874a6364aaae0b8442550360f4643579757cd60066c7eda53b01bd755"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sfragata/alertmanager-webhook-logger/releases/download/v1.0.0/alertmanager-webhook-logger_1.0.0_Darwin_arm64.tar.gz"
      sha256 "6effec3c2ec6281c7d440be7827c2f24b2ed698f9ce649ddad419179d8048d57"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sfragata/alertmanager-webhook-logger/releases/download/v1.0.0/alertmanager-webhook-logger_1.0.0_Linux_x86_64.tar.gz"
      sha256 "223e9e00ed4aebc23857cb1043bc800693bba393a29d2320931ca2881e2ee373"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sfragata/alertmanager-webhook-logger/releases/download/v1.0.0/alertmanager-webhook-logger_1.0.0_Linux_arm64.tar.gz"
      sha256 "3b7b7f5e8a551fac97dbfb734359001d4be4a1ad12853b417ba6e60d54863ec7"
    end
  end

  def install
    bin.install "alertmanager-webhook-logger"
  end
end
