# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerHubLimits < Formula
  desc "Utility to check docker download rate limits""
  homepage "https://github.com/sfragata/docker-hub-limits/"
  version "1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sfragata/docker-hub-limits/releases/download/v1.3/docker-hub-limits_1.3_Darwin_x86_64.tar.gz"
    sha256 "6309cc0b04cc4bfa103a83070da6ccb3ffea6da462ab807f29c394585ec90892"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sfragata/docker-hub-limits/releases/download/v1.3/docker-hub-limits_1.3_Linux_x86_64.tar.gz"
    sha256 "cf894490a0c5dbcd970fb04f11140f232603fbb14d040e996e621bc012d27c87"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/sfragata/docker-hub-limits/releases/download/v1.3/docker-hub-limits_1.3_Linux_arm64.tar.gz"
    sha256 "14e769fdcb12dd5381246180bd7ec73e51331b7f260af64480c4f1c873eb7fb4"
  end

  def install
    bin.install "docker-hub-limits"
  end
end
