# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlexExporter < Formula
  desc "Prometheus plex exporter"
  homepage "https://github.com/sfragata/plex_exporter/"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sfragata/plex_exporter/releases/download/v1.0.0/plex_exporter_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "3d615dc0e9a4f3e25e0a27f8ad8de4decfde7673f366d4320c5ac837dfdd65c4"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/sfragata/plex_exporter/releases/download/v1.0.0/plex_exporter_1.0.0_Darwin_arm64.tar.gz"
    sha256 "a2cd64df351ecbd16f7a8fa8dfa935038349eeb2e8803b5a15b3ab92be0d1816"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sfragata/plex_exporter/releases/download/v1.0.0/plex_exporter_1.0.0_Linux_x86_64.tar.gz"
    sha256 "58539e3b877c86e8b4d044b6deff087cf3d0fd4b7a7347906a58a69b75f52ef1"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/sfragata/plex_exporter/releases/download/v1.0.0/plex_exporter_1.0.0_Linux_arm64.tar.gz"
    sha256 "9fddc7a678d2bf965557639f65c3a4dfab80ee4d37fbd4cab5a80a7a447d2b07"
  end

  def install
    bin.install "plex_exporter"
  end
end
