# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlexExporter < Formula
  desc "Prometheus plex exporter"
  homepage "https://github.com/sfragata/plex_exporter/"
  version "1.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sfragata/plex_exporter/releases/download/v1.0.4/plex_exporter_1.0.4_darwin_amd64.tar.gz"
      sha256 "3e0c2d08aa479b576b9aa246b6a59ad5ac8430aff984e5db5af6ed85b3ecad52"

      def install
        bin.install "plex_exporter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sfragata/plex_exporter/releases/download/v1.0.4/plex_exporter_1.0.4_darwin_arm64.tar.gz"
      sha256 "4b21213150307e57d343859e7f5a0f7f5520ed34a96b0cbf2228e64c28c9b688"

      def install
        bin.install "plex_exporter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sfragata/plex_exporter/releases/download/v1.0.4/plex_exporter_1.0.4_linux_arm64.tar.gz"
      sha256 "6ccaf9226b8f9fed288d1ba6b86804eae1cf729d46e4b42bb84de9ab8395a990"

      def install
        bin.install "plex_exporter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sfragata/plex_exporter/releases/download/v1.0.4/plex_exporter_1.0.4_linux_amd64.tar.gz"
      sha256 "3d4855fd7b2fa86590c5a4e77babaeb986a36cfa620a3c7f968943d3730be082"

      def install
        bin.install "plex_exporter"
      end
    end
  end
end
